export const paymentModalStyles = {
  overlay: 'payment-modal-overlay fixed inset-0 z-[60] flex items-center justify-center p-6',
  modal: 'payment-modal w-full max-w-[560px] flex flex-col overflow-hidden',
  header: 'payment-modal-header flex items-center justify-between px-8 py-5 shrink-0',
  headerLeft: 'flex flex-col gap-1',
  title: 'payment-title',
  stepLabel: 'payment-step-label',
  body: 'flex flex-col gap-6 px-8 py-6 overflow-y-auto',
  footer: 'payment-modal-footer flex items-center justify-between px-8 py-5 shrink-0',
  sectionTitle: 'payment-section-title mb-2',
  section: 'flex flex-col gap-3',
  methodRow: 'flex gap-3',
  methodBtn: 'payment-method-btn flex-1 py-3 px-4',
  methodBtnSelected: 'payment-method-btn selected flex-1 py-3 px-4',
  field: 'flex flex-col gap-1',
  input: 'payment-input w-full px-4 py-2.5',
  inputError: 'payment-input error w-full px-4 py-2.5',
  inputRow: 'flex gap-3',
  error: 'payment-error',
  discountValid: 'payment-discount-valid',
  btnPrimary: 'payment-btn-primary px-6 py-2.5',
  btnSecondary: 'payment-btn-secondary px-6 py-2.5',
  btnConfirm: 'payment-btn-confirm px-6 py-2.5',
  btnPrefill: 'payment-btn-prefill px-3 py-1.5',
  summaryRow: 'payment-summary-row flex justify-between items-center',
  summaryTotal: 'payment-summary-total flex justify-between items-center',
  summaryDiscount: 'payment-summary-discount flex justify-between items-center',
  summaryDivider: 'payment-summary-divider w-full h-px my-2',
  resultWrapper: 'flex flex-col items-center gap-4 py-8',
  resultIcon: 'payment-result-icon',
  resultSuccess: 'payment-result-success text-center',
  resultError: 'payment-result-error text-center',
}